/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds/
 */

tasks {
  "hello" {
    group = "Custom"
    description = "this is hello"

    doLast {
      println("hello, mhf")
    }
  }

  "copy"(Copy::class) {
    group = "Custom"
    description = "Copies sources to the dest directory"
    dependsOn("hello")

    from("src")
    into("dest")
  }

  "custom"(CustomTask::class) {
    group = "Custom"
    description = "this is a custom task"

    text = "nice"
  }
}

task<Copy>("Copy") {
    group = "Custom"
    description = "Copies sources to the dest directory"

    from("src")
    into("dest")
}

defaultTasks("hello")

open class CustomTask: DefaultTask() {
  var text: String = ""

  @TaskAction
  fun greet() {
    println("CustomTask: ${text}")
  }
}
